[package]
name = "librcast"
version = "0.1.0"
authors = ["Bertrand \"Kamek\" Bousquet <b.kamek@gmail.com>"]

[dependencies]
failure = "0.1.1"
dns-parser = "0.7.1"
uuid = { version = "0.6", features = ["v4"] }